[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Velocidade do Monitor Serial
monitor_speed = 115200

; --- CONFIGURAÇÕES CRÍTICAS PARA O ESP32-S3 (16MB Flash) ---
build_flags = 
    ; Ativa o USB nativo para o Serial.print() funcionar no boot
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ; Ativa o suporte para a PSRAM
    -D BOARD_HAS_PSRAM

; Configura o tamanho correto da Flash para 16MB
board_upload.flash_size = 16MB

; Esquema de particionamento para liberar espaço dos 16MB (Exemplo com suporte a OTA e SPIFFS grande)
board_build.partitions = default_16MB.csv

; Define o tipo de conexão da PSRAM (Octal para a maioria das N16P/N16R8)
board_build.arduino.memory_type = qio_opi

; Bibliotecas Utilizadas no Projeto
lib_deps =
    fastled/FastLED@^3.6.0
    marcoschwartz/LiquidCrystal_I2C@^1.1.4